language: python
cache: pip

addons:
  apt:
    packages:
      - sqlite3
      - gdal-bin
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev

python:
  - "3.6"

branches:
  only:
    - master

before_install:
  - pip install -U pip wheel setuptools
  - pip install --no-cache-dir -U -r requirements-test.txt
  - ./runflake8
  - ./runisort

install:
  - python setup.py -q develop

script:
  - coverage run --source=openwisp_monitoring runtests.py
  ./tests/manage.py makemigrations monitoring device check --dry-run | grep "No changes detected";

after_success:
  coveralls
