language: python
dist: bionic
cache: pip

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=2.2,<3.0"
  - DJANGO="django>=3.0,<3.1"

addons:
  apt:
    packages:
      - sqlite3
      - fping
      - gdal-bin
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - spatialite-bin
      - libsqlite3-mod-spatialite

services:
  - docker
  - redis-server

branches:
  only:
    - master
    - dev

before_install:
  - docker run -d --name influxdb -e INFLUXDB_DB=openwisp2 -p 8086:8086 influxdb:alpine
  # TODO: Change the command to create 'openwisp2' database
  # - docker run -it --rm -v ~/victoria-metrics-data:/victoria-metrics-data -p 8428:8428 victoriametrics/victoria-metrics
  - pip install -U pip wheel setuptools
  - pip install $DJANGO
  - pip install -U -r requirements-test.txt

install:
  - pip install -e .
  # temporary: remove when openwisp-notifications is released
  - pip install -U https://github.com/openwisp/openwisp-notifications/tarball/master

script:
  - ./run-qa-checks
  - SAMPLE_APP=1 coverage run --source=openwisp_monitoring runtests.py
  - coverage run -a --source=openwisp_monitoring runtests.py

after_success:
  coveralls
