version: "3"

services:
  influxdb:
    image: influxdb:1.8-alpine
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: openwisp2
      INFLUXDB_USER: openwisp
      INFLUXDB_USER_PASSWORD: openwisp

  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes

  # TODO: Provide 'openwisp2' as db and authentication details
  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    ports:
      - "8428:8428"
    volumes:
      - victoria-metrics-data:/var/lib/victoria-metrics

volumes:
  influxdb-data:
  victoria-metrics-data:
